# Generated by Django 3.2 on 2021-04-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210422_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='foto',
        ),
    ]
