# Generated by Django 3.2 on 2021-04-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_producto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
    ]
